services:
  base:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    # environment:
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    # depends_on:
    #   - db
